DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
  USER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_NAME VARCHAR(60) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL,
  CR_DATE DATE,
  UP_DATE DATE,
  CR_BY VARCHAR(30) NOT NULL,
  UP_BY VARCHAR(30)
);

DROP TABLE IF EXISTS VIDEOS;
 
CREATE TABLE VIDEOS (
  VIDEO_ID VARCHAR(36)  PRIMARY KEY,
  USER_ID INT NOT NULL,
  TITLE VARCHAR(250),
  DESC VARCHAR(250),
  EXTENSION VARCHAR(5) NOT NULL,
  SIZE NUMBER NOT NULL,
  CR_DATE DATE,
  UP_DATE DATE,
  CR_BY VARCHAR(30) NOT NULL,
  UP_BY VARCHAR(30),
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);